### ISSUE TITLE
ethereum_transcations table data duplication

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footbase#273]
**Describe the bug**
ethereum_transcations table has duplicate data
**To Reproduce**
```
SELECT   hash,count(1)
FROM ethereum_transactions
WHERE block_timestamp >= timestamp '2022-01-01' AND block_timestamp < timestamp '2023-01-01'
group by hash
having count(1) > 1
```

**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/210356209-5a74c233-4ef7-4163-a6db-9d16f0350ee5.png)

### Severity
- [x] Highest
- [ ] High
- [ ] Middle
- [ ] Low

**Comment by RryanLH** [comment]
Reason: Because the data on the chain will have an operation to confirm the final state of the block, because we synchronize the chain data too fast, the block still has not done the confirmation operation, resulting in the acquisition of unconfirmed data, thus producing the wrong or duplicate data

Fix solution:reload data and adjust the logic of getting chain data
